"""Adicionando coluna 'valor_total' à tabela Combo

Revision ID: 3e73a9410a8b
Revises: 
Create Date: 2024-04-12 13:15:13.645312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e73a9410a8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combo', schema=None) as batch_op:
        batch_op.drop_column('tipo')
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###
